language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: UiuxItXN4B/vej4kdJgxXx/k5gRNGEISB7xVNstwuQ2NL+bI4oX8QabeSo/FHRSsGZR9dzrZnhvlvMwtkCjkWBaCSnnCP+mygcsFOynEhftz4GbIl4MUaqjJ2Yv4lU3X7Kcim4F4o3GIuhBvUpa0tLe3T3FZma+78oB89bxBAd9o+IxINA9QDZYYMcL9T49fzWlPO67HE4q3R1oaVOJPUHiFgrjiLoHiEGOj6G/oPzkD1EXwm8frZfu60NxbKMKw9BdJHnk5eoWp5C+X0e7xxuco3Bu+CYZyHUi/ksRXv+/4XdtDczzpS32ZMNoqumfUHwxKNE6+db24oGDFDrCGAFZpGvnTbxv2UAvIo1LKJrGBBfgG2YVPQoxXaSTyTAt3SoF8sGnCDO2tlIja7rE6/LSC6YEFdrQWUi+egwkYF7sFE/QMR07YiQsaI+PA0IxzAkjwH6Fb78WIUMMae5Cs6MjW9XpK8KaMv/9tp79maJ1DvHYIX+5jZw/60slxm4lU4iuOKlOl+gwwuekSTkpsjytcOwAHqkJgXwKmFUW7K7be2frDO71tOZBq/rh50g2bIvj/uqitABnpz55o0DkzZkTk5jkNS6QYuzRU+9JLuA3KlbOdJ8ZPRpZ/d0qMww8Jvk89X0qsUQTwngYwO9RS7ZeDh5iR50e2D+p/k30zq0Q=
  - secure: QYHmOt1mPFCS/5mDdTeq7eYqzfI89+zL40SSzH67wjxa3zn9Wu/0kL/qxCYSWQ6NemkOqr1Y8JiypV43wI46OB4FVhHGF3cKeWZ+n+KN4k+HBtg3dxAG+wD0cu5Ib0U3/2U+vVC8fksp9FRbqcyFy1iUXHaDGVHfGCFIRlCWOO86kg/hlbP0C6kBNxLrJm80Zx7mHNkLCohCOQFockdzVToJqhJ6olULbw4owAzxAO3YsG3INuz38893caaPPD/HsJVu89IHGHms0n2Wybc5lc+l1ullJ6eBI+RVdiB7BEhvHEoEHUz09e/a1oe8BKFUaMNNM3nVHVdTkfSuiXf1N+tt/FveHJJpokAB9/KJR8BDLLQGkb2f6iSk8i/glBhEwuipHPXxg2BIZ72YEUc+5fsb66DEwCBDtWQjxv1q5lRVB1s7KvMvYW3cA5a64X1fVvivLDG+ikpbfa1Sr0kljDaWYJWnlNbwSbwC4RtmlNlWoUJR113PYR8t4w3C4BkLkOqNEIk63bivtOK48w9aIwgtLuMMLjCSvOpr9duOVfTi70WEGVgxcfNR9WdtU2Q3Gg1OoyAqGMqjIJxFkFteKT1ng4+u361fkM7kZY34gIhFRrn//hGzsDuhcxpL79tqLqBAUWY6tezZZHK7/4H7KK/y5jFojU4KngMKnNz3eu4=
