baseurl: https://www.recaffeinate.co/
languageCode: en-us
metaDataFormat: yaml
title: recaffeinate
disqusShortname: recaffeinate
params:
  stylizedTitle: '<span class="color-lightgray">recaffei</span><span class="color-darkgray">nate</span>'
  description: the blog and website of Nate Barbettini
  googleAnalyticsTrackingId: UA-103155569-1
  keepReading: keep reading...
  defaultPageImage: /img/coffee.png
  navLinks:
    - title: About
      url: /about
    - title: ASP.NET Core Book
      url: /book
    - title: Courses
      url: https://www.linkedin.com/learning/instructors/nate-barbettini
    - title: youtube
      url: https://www.youtube.com/playlist?list=PLLRFyxYl_5YjpoPB1ryUbrCM7tmKFUNBV
    - title: twitter
      url: https://twitter.com/nbarbettini
taxonomies:
  tag: tags
  series: series
author:
  name: Nate Barbettini
  bio: Author, teacher, and full-stack developer. Microsoft MVP (2017-2019). California-born, Texas-raised.
  email: nate@barbettini.com
