baseurl: https://www.recaffeinate.co/
languageCode: en-us
metaDataFormat: yaml
title: recaffeinate
disqusShortname: recaffeinate
params:
  stylizedTitle: '<span class="color-lightgray">recaffei</span><span class="color-darkgray">nate</span> <img src="/img/coffee.png" class="title-coffee-icon">'
  description: the blog and website of Nate Barbettini
  googleAnalyticsTrackingId: UA-103155569-1
  keepReading: keep reading...
  pageimage: /img/coffee.png
  navLinks:
    - title: About
      url: /about
    - title: ASP.NET Core Book
      url: /book
    - title: Talks
      url: https://speakerdeck.com/nbarbettini
    - title: Github
      url: https://github.com/nbarbettini
author:
  name: Nate Barbettini
  bio: Author, teacher, and full-stack developer. Microsoft MVP. California-born, Texas-raised.
  email: nathanaelb@gmail.com
